version: "3"

services:
  dns:
    build: ././bind
    image: centos_bind:1
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    expose:
      - 53/tcp
      - 53/udp
    networks:
      docker_network:
        ipv4_address: 172.18.0.2
    privileged: true
    restart: always
    
  web:
    build: ././apache
    image: centos_apache:1
    container_name: apache
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      docker_network:
        ipv4_address: 172.18.0.3
    privileged: true
    restart: always

networks:
  docker_network:
    name: docker_network
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.18.0.0/16